name: Asp.net Core CI

on : [push]

jobs:
  build:
   runs-on: windows-2019
  
   steps : 
    - uses: actions/checkout@v1
    - name: Setup .Net Core
      uses: actions/setup-dotnet@v1
      with:
       dotnet-version: 5.0
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Run Test
      run: dotnet test --configuration Release
  
